/**
 * Registry of the ecosystem apps, served to the Jarvis dashboard manager
 * behind the Jarvis key (it lists local development URLs).
 */
export const ECOSYSTEM_APPS = [
  {
    id: 'second-brain',
    name: 'Jarvis Second Brain AI Core',
    slug: 'second-brain',
    category: 'ai_core',
    status: 'operational',
    localUrl: 'http://localhost:3005',
    productionUrl: 'https://jarvis.savestate.co.za',
    healthEndpoint: 'http://localhost:3005/api/system/status',
    description: 'Central AI assistant, autonomous triage sentry, vector memory, and execution runtime.',
    portalEmbedUrl: 'http://localhost:3005/m/control',
    capabilities: ['autonomous_actions', 'email_triage', 'webhook_gateway', 'voice_pipeline'],
  },
  {
    id: 'agent-builder',
    name: 'Agent Builder (PC & Remote)',
    slug: 'agent-builder',
    category: 'ai_core',
    status: 'operational',
    productionUrl: 'https://agent-builder-remote.vercel.app',
    description: 'Visual autonomous agent designer, prompt flow orchestrator, and tool synthesizer.',
    portalEmbedUrl: 'https://agent-builder-remote.vercel.app',
    capabilities: ['prompt_engineering', 'agent_orchestration', 'ide_bridge', 'code_synthesis'],
  },
  {
    id: 'consolidated-hub',
    name: 'Consolidated Business Hub',
    slug: 'consolidated-hub',
    category: 'saas_platform',
    status: 'operational',
    localUrl: 'http://localhost:9003',
    productionUrl: 'https://consolidated-hub.vercel.app',
    description: 'Master enterprise hub managing ARP Cloud Solutions, client projects, invoices, and payments.',
    portalEmbedUrl: 'https://consolidated-hub.vercel.app/admin',
    capabilities: ['invoicing', 'client_crm', 'payfast_gateway', 'firebase_sync'],
  },
  {
    id: 'aethermail',
    name: 'AetherMail Business Gateway',
    slug: 'aethermail',
    category: 'productivity',
    status: 'operational',
    localUrl: 'http://localhost:3007',
    productionUrl: 'https://aethermail-five.vercel.app',
    description: 'Autonomous email triage, Stalwart relay, IMAP synchronization, and spam firewall.',
    portalEmbedUrl: 'https://aethermail-five.vercel.app',
    capabilities: ['smtp_relay', 'imap_sync', 'smart_drafting', 'domain_management'],
  },
  {
    id: 'cvgenman',
    name: 'Emeron CV Parsing & Generation Engine',
    slug: 'cvgenman',
    category: 'saas_platform',
    status: 'operational',
    productionUrl: 'https://cvgenman.vercel.app',
    description: 'AI-assisted resume parser, professional CV builder, and portfolio synchronization webhook.',
    portalEmbedUrl: 'https://cvgenman.vercel.app',
    capabilities: ['resume_parsing', 'pdf_export', 'webhook_sync', 'candidate_scoring'],
  },
  {
    id: 'remotedesk',
    name: 'RemoteDesk Enterprise Workspace',
    slug: 'remotedesk',
    category: 'productivity',
    status: 'operational',
    productionUrl: 'https://remotedesk-omega.vercel.app',
    description: 'Remote desktop gateway, cloud file sync, and team collaboration canvas.',
    portalEmbedUrl: 'https://remotedesk-omega.vercel.app',
    capabilities: ['session_streaming', 'file_vault', 'multi_user_collab'],
  },
  {
    id: 'financeplay',
    name: 'FinancePlay Analytics',
    slug: 'financeplay',
    category: 'saas_platform',
    status: 'operational',
    productionUrl: 'https://www.xpfinance.co.za',
    description: 'Personal and corporate finance modeling, expense classification, and budget forecasting.',
    portalEmbedUrl: 'https://www.xpfinance.co.za',
    capabilities: ['transaction_categorization', 'budgeting', 'financial_reports'],
  },
  {
    id: 'deenify',
    name: 'Deenify Spiritual Lifestyle',
    slug: 'deenify',
    category: 'consumer',
    status: 'operational',
    productionUrl: 'https://www.deenify.co.za',
    description: 'Islamic companion app featuring prayer timings, Qibla compass, and Quran recitation.',
    portalEmbedUrl: 'https://www.deenify.co.za',
    capabilities: ['prayer_times', 'quran_audio', 'community_events'],
  },
  {
    id: 'project-cupid',
    name: 'Project Cupid / Muslim Dating',
    slug: 'project-cupid',
    category: 'consumer',
    status: 'operational',
    productionUrl: 'https://muslim-dating.vercel.app',
    description: 'Modern, values-aligned matchmaking and marital relationship platform.',
    portalEmbedUrl: 'https://muslim-dating.vercel.app',
    capabilities: ['profile_matching', 'direct_messaging', 'verification'],
  },
  {
    id: 'myportfolio',
    name: 'Mohamed Raaziq Parker Portfolio (Self)',
    slug: 'myportfolio',
    category: 'productivity',
    status: 'operational',
    productionUrl: 'https://portfolio.arpcloudsolutions.co.za',
    description: 'Showcase portfolio, tech stack matrix, CV synchronization, and ecosystem dashboard hub.',
    portalEmbedUrl: 'https://portfolio.arpcloudsolutions.co.za/?portal=true',
    capabilities: ['cv_sync', 'telemetry_export', 'jarvis_bridge', 'dashboard_manager'],
  },
];
